// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/partners": {
            "post": {
                "description": "新しいパートナーを作成し、初期ステータスを登録します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "partners"
                ],
                "summary": "パートナー新規作成",
                "parameters": [
                    {
                        "description": "作成情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_interface_handler.CreatePartnerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/girlfriend-backend_internal_domain_model.Partner"
                        }
                    }
                }
            }
        },
        "/partners/{id}": {
            "get": {
                "description": "指定されたIDのパートナーのステータス情報を返します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "partners"
                ],
                "summary": "パートナー情報の取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Partner ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/girlfriend-backend_internal_domain_model.Partner"
                        }
                    }
                }
            }
        },
        "/partners/{id}/memories": {
            "get": {
                "description": "指定されたIDのパートナーの思い出ログ一覧を返します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "partners"
                ],
                "summary": "思い出の取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Partner ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/girlfriend-backend_internal_domain_model.Memory"
                            }
                        }
                    }
                }
            }
        },
        "/partners/{id}/voices": {
            "get": {
                "description": "パートナーの性格に基づいたセリフと音声URLを取得します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "partners"
                ],
                "summary": "ボイス一覧の取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Partner ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/girlfriend-backend_internal_domain_model.VoiceLine"
                            }
                        }
                    }
                }
            }
        },
        "/sleep/end": {
            "post": {
                "description": "睡眠を終了し、睡眠時間を計算して記録します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sleep"
                ],
                "summary": "おはよう（起床）",
                "parameters": [
                    {
                        "description": "パートナーID",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_interface_handler.SleepRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/girlfriend-backend_internal_domain_model.SleepLog"
                        }
                    }
                }
            }
        },
        "/sleep/start": {
            "post": {
                "description": "指定されたパートナーの睡眠計測を開始します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sleep"
                ],
                "summary": "おやすみ（睡眠開始）",
                "parameters": [
                    {
                        "description": "パートナーID",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_interface_handler.SleepRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/girlfriend-backend_internal_domain_model.SleepLog"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "girlfriend-backend_internal_domain_model.Memory": {
            "type": "object",
            "properties": {
                "generated_prompt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "occurred_at": {
                    "type": "string"
                },
                "partner_id": {
                    "type": "string"
                },
                "scenario_id": {
                    "type": "string"
                }
            }
        },
        "girlfriend-backend_internal_domain_model.Partner": {
            "type": "object",
            "properties": {
                "current_stage": {
                    "type": "string"
                },
                "hair_color": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "intelligence": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "personality": {
                    "type": "string"
                },
                "sense": {
                    "type": "integer"
                },
                "stamina": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "string"
                },
                "voice_type": {
                    "type": "string"
                }
            }
        },
        "girlfriend-backend_internal_domain_model.SleepLog": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "partner_id": {
                    "type": "string"
                },
                "sleep_minutes": {
                    "description": "同上",
                    "type": "integer"
                },
                "slept_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "wake_at": {
                    "description": "まだ起きてない時はNULLなのでポインタ",
                    "type": "string"
                }
            }
        },
        "girlfriend-backend_internal_domain_model.VoiceLine": {
            "type": "object",
            "properties": {
                "audio_url": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "line_text": {
                    "type": "string"
                },
                "personality": {
                    "type": "string"
                },
                "situation": {
                    "type": "string"
                }
            }
        },
        "internal_interface_handler.CreatePartnerRequest": {
            "type": "object",
            "properties": {
                "hair_color": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "personality": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "voice_type": {
                    "type": "string"
                }
            }
        },
        "internal_interface_handler.SleepRequest": {
            "type": "object",
            "properties": {
                "partner_id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Girlfriend Backend API",
	Description:      "美少女育成ゲームのバックエンドAPIです。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
